# Generated by Django 5.1.4 on 2025-06-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='number_of_servings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
