# Generated by Django 5.2.3 on 2025-06-26 07:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_foodentry_number_of_servings'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.food'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyentry',
            unique_together={('user_profile', 'date')},
        ),
    ]
