# Generated by Django 5.2.3 on 2025-06-26 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_foodentry_time_alter_food_name_alter_foodentry_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
